# Workflow for Automatically building and pushing EEs to a registry based on repo changes
# 

name: Buld and Push EE to a registry


on:
  # Triggers the workflow on push
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ee:
    runs-on: ubuntu-latest
    steps:

      - name: Logging Output
        run: Beginning EE Build Job
        
      - name: Check-out repo
        uses: actions/checkout@v3

      - name: boot strap ansible-builder
        run: pip install ansible-builder

      - name: Build image
        id: build-image
        working-directory: ${{ inputs.EE_FOLDER_NAME }}
        run: |
          ansible-builder build 
          --tag=${{ inputs.EE_FOLDER_NAME }}:${{ inputs.EE_IMAGE_TAG }} 
          
          
      
      - name: Push To Registry
        # You may pin to the exact commit or the version.
        # uses: redhat-actions/push-to-registry@9e8327fcde18a44143eda2e7dfe68eca01aeeeea
        uses: redhat-actions/push-to-registry@v2.7
        with:
          # Name of the image/manifest to push (e.g. username/imagename or imagename)
          image: # optional
          # 'The tag or tags of the image/manifest to push. For multiple tags, seperate by whitespace. For example, "latest v1"'
          tags: # optional, default is latest
          # Hostname and optional namespace to push the image to (eg. quay.io/username or quay.io)
          registry: # optional
          # Username to use as credential to authenticate to the registry
          username: # optional
          # Password to use as credential to authenticate to the registry
          password: # optional
          # Verify TLS certificates when contacting the registry
          tls-verify: # optional, default is true

